Repository calvin-cs262-fall2020-teamH/habitbuddy-client, pull requests merged in 2020-11, with the labels that each got.

#28 Temp/habit tracking
  screens/habittrack.js
  shared/habittrackBlock.js
Labels: enhancement, update

#34 Cleaning/home
  screens/buddies.js
  screens/buddyDetails.js
  screens/home.js
Labels: enhancement, update

#38 Updated style of login and signup screens
  package-lock.json
  package.json
  routes/authStack.js
  screens/editProfile.js
  screens/emptyHabits.js
  screens/emptyProfile.js
  screens/login.js
  styles/global.js
Labels: enhancement, update

#39 Backend work
  package-lock.json
  package.json
  routes/buddiesStack.js
  routes/habittrackStack.js
  routes/homeStack.js
  routes/settingsStack.js
  screens/buddyDetails.js
  screens/editProfile.js
  screens/profile.js
  styles/global.js
Labels: enhancement, update

#37 Temp/habittrackinfo
  package-lock.json
  package.json
  routes/buddiesStack.js
  routes/habittrackStack.js
  routes/homeStack.js
  routes/profileStack.js
  routes/settingsStack.js
  screens/aboutHabittrack.js
  screens/habittrack.js
  screens/home.js
  shared/card.js
  shared/habittrackBlock.js
Labels: enhancement, update

#35 Quality of Life Update
  .dccache
  assets/splash.png
  assets/splash2.png
  package-lock.json
  package.json
  routes/authStack.js
  routes/homeStack.js
  routes/tab.js
  screens/buddies.js
  screens/emptyHabits.js
  screens/habittrack.js
  screens/home.js
  screens/settingsScreens/theme.js
  shared/card.js
  shared/circleCard.js
  styles/global.js
Labels: update

#36 Added the ability to swap between themes
  .dccache
  .gitignore
  App.js
  package-lock.json
  package.json
  routes/authStack.js
  routes/settingsStack.js
  routes/tab.js
  screens/buddies.js
  screens/buddyDetails.js
  screens/editProfile.js
  screens/emptyHabits.js
  screens/emptyProfile.js
  screens/habittrack.js
  screens/home.js
  screens/login.js
  screens/profile.js
  screens/settings.js
  screens/settingsScreens/about.js
  screens/settingsScreens/account.js
  screens/settingsScreens/changePassword.js
  screens/settingsScreens/theme.js
  shared/blocks/alertBlock.js
  shared/blocks/selectionBlock.js
  shared/blocks/settingsBlock.js
  shared/blocks/switchBlock.js
  shared/card.js
  shared/editProfileCard.js
  shared/habittrackBlock.js
  shared/profileCard.js
  shared/profileLinkingCard.js
  styles/global.js
Labels: enhancement, update

#50 Updates/backend prep
  screens/buddies.js
  screens/buddyDetails.js
  screens/home.js
  screens/profile.js
Labels: enhancement, update

#51 Updated the client to work with the backend
  package-lock.json
  package.json
  screens/buddies.js
  screens/buddyDetails.js
  screens/editProfile.js
  screens/home.js
  screens/profile.js
Labels: enhancement, update

#49 Added Local Storage and Login functionality
  App.js
  data/CommonDataManager.js
  package-lock.json
  package.json
  routes/authStack.js
  routes/homeStack.js
  routes/tab.js
  screens/buddies.js
  screens/editProfile.js
  screens/home.js
  screens/login.js
  screens/profile.js
  screens/settingsScreens/account.js
  screens/settingsScreens/changePassword.js
  screens/signUpHabit.js
  screens/signUpProfile.js
Labels: enhancement

#54 update HabitTrack
  routes/habitTrackStack.js
  screens/habitTrack.js
  shared/buddiesStreakCard.js
  shared/habitTrackBlock.js
Labels: enhancement, update

#52 added info on HabitStack
  screens/home.js
Labels: enhancement, update
