Repository calvin-cs262-fall2020-teamH/habitbuddy-client, pull requests merged in 2020-10, with the labels that each got.

#19 created login, emptyProfile, and emptyHabits
  package-lock.json
  routes/aboutStack.js
  routes/drawer.js
  routes/loginStack.js
  routes/settingsStack.js
  screens/emptyHabits.js
  screens/emptyProfile.js
  screens/login.js
  styles/global.js
Labels: enhancement

#20 Added alertBlock and Change Password page
  routes/settingsStack.js
  screens/habittrack.js
  screens/home.js
  screens/settings.js
  screens/settingsScreens/about.js
  screens/settingsScreens/account.js
  screens/settingsScreens/changePassword.js
  screens/settingsScreens/theme.js
  shared/blocks/alertBlock.js
  shared/blocks/selectionBlock.js
  shared/blocks/settingsBlock.js
  shared/blocks/switchBlock.js
  shared/switchBlock.js
  styles/global.js
Labels: bug, enhancement

#21 updated the UI for profile page
  .idea/vcs.xml
  .idea/workspace.xml
  App.js
  routes/profileStack.js
  screens/editProfile.js
  screens/profile.js
  shared/editProfileCard.js
  shared/profileCard.js
  styles/global.js
Labels: enhancement

#23 added droplist and changed globalstyles
  package-lock.json
  package.json
  screens/emptyHabits.js
  styles/global.js
Labels: enhancement

#24 Updates/home
  routes/homeStack.js
  screens/buddies.js
  screens/buddyDetails.js
  screens/home.js
  shared/circleCard.js
  shared/profile.js
Labels: documentation, enhancement

#25 Updated navigation to incorporate the Login page
  routes/drawer.js
  routes/homeStack.js
  routes/loginStack.js
  screens/emptyHabits.js
  screens/emptyProfile.js
  screens/home.js
  screens/login.js
  screens/settingsScreens/changePassword.js
  styles/global.js
Labels: enhancement

#27 Temp/update buddies profile
  .idea/workspace.xml
  screens/buddies.js
  screens/buddyDetails.js
  screens/editProfile.js
  screens/profile.js
  shared/editProfileCard.js
  shared/profileCard.js
  styles/global.js
Labels: enhancement

#29 updated about page with new vision statement
  screens/settingsScreens/about.js
Labels: update

#32 Changed from Drawer to Tab navigator and created an Authentication flow
  App.js
  package-lock.json
  package.json
  routes/authStack.js
  routes/drawer.js
  routes/habitSelectorStack.js
  routes/homeStack.js
  routes/profileStack.js
  routes/tab.js
  screens/Loading.js
  screens/buddyDetails.js
  screens/editProfile.js
  screens/emptyHabits.js
  screens/home.js
  screens/login.js
  shared/card.js
  shared/globalVars.js
  shared/header.js
  styles/global.js
Labels: enhancement, update
