Repository calvin-cs262-fall2020-teamH/habitbuddy-client, pull requests merged in 2020-12, with the labels that each got.

#55 Fixed Dynamic Styles not being applied to Habit Track screen
  screens/habitTrack.js
  shared/habitTrackBlock.js
Labels: bug

#57 Cleaned up issues with warnings and extra files
  data/CommonDataManager.js
  routes/authStack.js
  routes/settingsStack.js
  routes/tab.js
  screens/buddies.js
  screens/buddyDetails.js
  screens/home.js
  screens/login.js
  screens/settingsScreens/changePassword.js
  screens/settingsScreens/theme.js
  screens/signUpHabit.js
  shared/blocks/selectionBlock.js
  shared/card.js
  shared/circleCard.js
  shared/habitTrackBlock.js
  styles/global.js
Labels: bug, update

#56 Set up changes for the user test
  data/CommonDataManager.js
  screens/home.js
  screens/login.js
  screens/signUpHabit.js
Labels: enhancement, update

#59 Updated settings page/stack
  routes/settingsStack.js
  screens/habitTrack.js
  screens/settings.js
  screens/settingsScreens/account.js
  screens/settingsScreens/changePassword.js
  screens/signUpProfile.js
  shared/buddiesStreakCard.js
  shared/passwordInput.js
  styles/global.js
Labels: enhancement, update

#62 Changed the habitgoal to habit.
  screens/buddies.js
  screens/buddyDetails.js
  screens/profile.js
Labels: update

#63 UI clarification
  routes/buddiesStack.js
  screens/buddies.js
  screens/habitTrack.js
  styles/global.js
Labels: enhancement, update

#65 Fixed the habit tracker
  routes/habitTrackStack.js
  screens/buddies.js
  screens/habitTrack.js
Labels: enhancement, update

#68 updated readme
  README.md
Labels: documentation, update

#67 Password Confirmation
  assets/images/george.jpg
  screens/settingsScreens/changePassword.js
  screens/signUpProfile.js
Labels: enhancement, update

#66 Added real-time updates of Streak count and streak storage
  data/CommonDataManager.js
  routes/authStack.js
  routes/tab.js
  screens/habitTrack.js
  screens/home.js
  shared/habitTrackBlock.js
Labels: enhancement

#64 Made signup functional
  screens/signUpHabit.js
  screens/signUpProfile.js
Labels: enhancement, update

#71 Added the ability to delete buddies
  data/CommonDataManager.js
  routes/buddiesStack.js
  screens/buddies.js
  screens/buddyDetails.js
Labels: enhancement

#74 change password in settings now changes password
  screens/settingsScreens/changePassword.js
Labels: enhancement, update

#75 Wrote documentation on pretty much everything
  App.js
  package-lock.json
  routes/authStack.js
  routes/buddiesStack.js
  routes/habitTrackStack.js
  routes/homeStack.js
  routes/profileStack.js
  routes/settingsStack.js
  routes/tab.js
  screens/Loading.js
  screens/buddies.js
  screens/buddyDetails.js
  screens/editProfile.js
  screens/habitTrack.js
  screens/home.js
  screens/login.js
  screens/profile.js
  screens/settings.js
  screens/settingsScreens/about.js
  screens/settingsScreens/account.js
  screens/settingsScreens/changePassword.js
  screens/settingsScreens/theme.js
  screens/signUpHabit.js
  screens/signUpProfile.js
  shared/blocks/alertBlock.js
  shared/blocks/habitTrackBlock.js
  shared/blocks/selectionBlock.js
  shared/blocks/settingsBlock.js
  shared/blocks/switchBlock.js
  shared/buddiesStreakCard.js
  shared/card.js
  shared/editProfileCard.js
  shared/header.js
  shared/passwordInput.js
  shared/profileCard.js
  shared/profileLinkingCard.js
  styles/global.js
Labels: documentation
